Repository doctrine/event-manager, pull requests merged in 2018-06, with the labels that each got.

#1 Add Scrutinizer CI
  .scrutinizer.yml
Labels: enhancement

#2 Apply Doctrine CS 4.0 + test for removeEventSubscriber() & unknown event dispatching
  .gitattributes
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  lib/Doctrine/Common/EventArgs.php
  lib/Doctrine/Common/EventManager.php
  lib/Doctrine/Common/EventSubscriber.php
  phpcs.xml.dist
  tests/Doctrine/Tests/Common/EventManagerTest.php
  tests/Doctrine/Tests/DoctrineTestCase.php
  tests/Doctrine/Tests/TestInit.php
Labels: enhancement

#3 Update badges
  README.md
Labels: enhancement

#5 Add new docs for the event manager project.
  docs/en/index.rst
  docs/en/reference/index.rst
  docs/en/reference/overview.rst
  docs/en/sidebar.rst
Labels: Documentation

#6 Update homepage & tags
  composer.json
Labels: Improvement

#7 Conflict with doctrine/common pre-2.9
  composer.json
  composer.lock
Labels: Improvement

#8 Fix: Typo
  docs/en/reference/index.rst
Labels: Documentation

#9 Enhancement: Improve wording
  docs/en/reference/index.rst
Labels: Documentation

#10 Newer PHPUnit, fix non-static assert
  composer.json
  composer.lock
  tests/Doctrine/Tests/Common/EventManagerTest.php
Labels: Improvement
