Repository doctrine/event-manager, pull requests merged in 2022-10, with the labels that each got.

#48 Bump tools and CI workflows
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  composer.json
  phpcs.xml.dist
Labels: CI

#49 Flatten directory structure
  composer.json
  phpcs.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
  psalm.xml
  src/EventArgs.php
  src/EventManager.php
  src/EventSubscriber.php
  tests/Doctrine/Tests/DoctrineTestCase.php
  tests/EventManagerTest.php
Labels: Improvement

#52 Remove PHPStan suffix
  .github/workflows/static-analysis.yml
Labels: CI

#50 Split `getAllListeners()` out of `getListeners()`
  UPGRADE.md
  composer.json
  src/EventManager.php
  tests/EventManagerTest.php
Labels: Deprecation

#54 Revert return type on `EventSubscriber::getSubscribedEvents()`
  phpcs.xml.dist
  src/EventSubscriber.php
Labels: Improvement

#55 Setup composer lint
  .github/workflows/composer-lint.yml
  composer.json
Labels: CI

#57 Made the `$event` parameter of `EventManager::getListeners()` mandatory
  UPGRADE.md
  src/EventManager.php
  tests/EventManagerTest.php
Labels: BC Break

#59 Remove doctrine/deprecations
  composer.json
Labels: Improvement

#61 Failsafe for unknown event
  src/EventManager.php
  tests/EventManagerTest.php
Labels: Improvement
