Repository doctrine/event-manager, pull requests merged in 2024-05, with the labels that each got.

#66 Setup dependabot
  .doctrine-project.json
  .github/dependabot.yml
  .github/workflows/continuous-integration.yml
Labels: CI

#68 Doctrine CS 12
  composer.json
  phpcs.xml.dist
Labels: Static Analysis

#69 Psalm 5.24
  composer.json
  psalm-baseline.xml
  psalm.xml
Labels: Static Analysis

#70 PHPUnit 10.5
  .gitignore
  composer.json
  phpunit.xml.dist
Labels: Test Suite
